[package]
name = "rq-core"
version = "0.1.0"
edition = "2021"
authors = ["Brian Mayo <protiumx@gmail.com>"]
description = "rq-core includes parser and request calls"
readme = "README.md"

[dependencies]
pest = "2.1.3"
pest_derive = "2.0"

reqwest = { version = "0.11", features = ["json"] }
