name: rq-core
on:
  pull_request:
    paths:
      - .github/workflows/rq-core.yml
      - rq-core/**/*.rs
      - rq-core/**/cargo.toml
      - '!**/*.http'
    
  push:
    paths:
      - .github/workflows/rq-core.yml
      - rq-core/**/*.rs
      - rq-core/**/cargo.toml
      - '!**/*.http'
    branches:
      - main


concurrency:
  group: rq-core-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  CI:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "rq-core"
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Run cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-targets -- -D warnings

      - name: Run cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
